services:
  postgres:
    image: postgres:15-alpine
    restart: always
    env_file: static/environment/.env.postgres
    ports:
      - '5432:5432'
    volumes:
      - .:/app:ro
      - ./ci/init/pg_init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    healthcheck:
      test: "pg_isready -q -h postgres"
      interval: 1s
      timeout: 1s
      retries: 5

  redis:
    image: redis:7.0
    restart: always
    command: redis-server --loglevel warning
    ports:
      - '6379:6379'

  postgres_ui:
    image: sosedoff/pgweb
    restart: always
    env_file: static/environment/.env.postgres
    ports:
      - "5433:8081"
    depends_on:
      postgres:
        condition: service_healthy

  jaeger:
    image: jaegertracing/all-in-one:latest
    env_file: static/environment/.env.jaeger
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "9000:8080"
    env_file: static/environment/.env.swagger
    volumes:
      - ./openapi.yaml:/openapi.yaml:ro
      - ./static/environment/swagger.init.sh:/docker-entrypoint.d/__init.sh:ro