services:
  - type: web
    name: api
    runtime: rust
    region: frankfurt
    plan: starter
    healthCheckPath: /healthz
    buildCommand: cargo build --release
    startCommand: cargo run --release
    envVars:
      - key: RUST_LOG
        value: error
      - key: OAUTH_DOMAIN
        sync: false
      - key: OAUTH_AUDIENCE
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: TELEMETRY_ENABLED
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

databases:
  - name: postgres
    region: frankfurt
    plan: starter
    user: clapton
    postgresMajorVersion: 15
    ipAllowList: [ ]